name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/nativeSources/**'
      - '.github/workflows/*_Build.yml'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/nativeSources/**'
      - '.github/workflows/*_Build.yml'

env:
  JAR_FILE: Box3D-JavaFFM-0.1.0-jar-with-dependencies.jar
  EXAMPLE_CLASS: volucris.bindings.box3d.HelloBox3D

jobs:
  Linux_x64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK 26
      uses: actions/setup-java@v5
      with:
        java-version: '26'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Execute the HelloBox3D example
      run: |
        $JAVA_HOME/bin/java --enable-preview --enable-native-access=ALL-UNNAMED \
          -cp target/$JAR_FILE $EXAMPLE_CLASS

  Linux_Arm64:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK 26
      uses: actions/setup-java@v5
      with:
        java-version: '26'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Execute the HelloBox3D example
      run: |
        $JAVA_HOME/bin/java --enable-preview --enable-native-access=ALL-UNNAMED \
          -cp target/$JAR_FILE $EXAMPLE_CLASS

  macOS_Arm64:
    runs-on: macos-26
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK 26
      uses: actions/setup-java@v5
      with:
        java-version: '26'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Execute the HelloBox3D example
      run: |
        $JAVA_HOME/bin/java --enable-preview --enable-native-access=ALL-UNNAMED \
          -cp target/$JAR_FILE $EXAMPLE_CLASS
          
  macOS_x64:
    runs-on: macos-26-intel
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK 26
      uses: actions/setup-java@v5
      with:
        java-version: '26'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Execute the HelloBox3D example
      run: |
        $JAVA_HOME/bin/java --enable-preview --enable-native-access=ALL-UNNAMED \
          -cp target/$JAR_FILE $EXAMPLE_CLASS

  Windows_x64:
    runs-on: windows-2025
    steps:
    - uses: actions/checkout@v7
    - name: Set up JDK 26
      uses: actions/setup-java@v5
      with:
        java-version: '26'
        distribution: 'oracle'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      shell: bash
    - name: Execute the HelloWorld app
      run: |
        $JAVA_HOME/bin/java --enable-preview --enable-native-access=ALL-UNNAMED \
          -cp target/$JAR_FILE $EXAMPLE_CLASS
      shell: bash
